### ISSUE TITLE
[GitHub Actions] Cache, Yarn, and node_modules

### ISSUE THREAD

**Issue by zw627** [zw627/boilerplate-react-redux-ts-scss#873]
## Description

Follow the GitHub Actions Cache [documentation](https://github.com/actions/cache/blob/main/examples.md#node---yarn) for Yarn results in `node_modules` not existing:

```yaml
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get Cache
        uses: actions/cache@v2.1.3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
```

```shell
Run yarn test
yarn run v1.22.5
$ jest --coverage
/bin/sh: 1: jest: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 127.
```

## Cause

`actions/cache@v2.1.3` only caches and restores the yarn cache directory, it doesn't cache the `node_modules` directory.

## Solution

Use `yarn --prefer-offline` if cache is found, otherwise, use `yarn install --frozen-lockfile`.

## References

- https://github.com/yarnpkg/yarn/issues/6398
- https://stackoverflow.com/questions/61010294/how-to-cache-yarn-packages-in-github-actions
